name: Ruby CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.4.10', '2.5.7']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Upgrade RubyGems
      run: gem update --system 3.2.3


    - name: Install dependencies
      run: |
        gem install bundler:1.17.3
        bundle install

    - name: Install dummy app dependencies
      run: |
        bundle install --gemfile=$PWD/spec/dummy/Gemfile

    - name: Run tests
      run: bundle exec rake